# Generated by Django 6.0.1 on 2026-02-26 03:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(limit_choices_to={'tipo': 'MP'}, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='stock.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, help_text='Motivo del consumo, ej: venta, muestra, etc.', max_length=75)),
                ('producto', models.ForeignKey(limit_choices_to={'tipo': 'PT'}, on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='stock.producto')),
            ],
        ),
    ]
