# Generated by Django 6.0.1 on 2026-03-12 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_compra_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='stock.producto'),
        ),
    ]
