# Generated by Django 6.0.1 on 2026-04-17 18:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso')], max_length=1)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría de movimiento',
                'verbose_name_plural': 'Categorías de movimientos',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('caja', 'Caja'), ('banco', 'Banco'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='caja', max_length=10)),
                ('moneda', models.CharField(default='ARS', max_length=3)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='GastoRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('meses', models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(limit_choices_to={'tipo': 'E'}, on_delete=django.db.models.deletion.PROTECT, to='finanzas.categoriamovimiento')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.cuenta')),
            ],
            options={
                'verbose_name': 'Gasto recurrente',
                'verbose_name_plural': 'Gastos recurrentes',
                'ordering': ['-fecha_inicio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso')], max_length=1)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('documento', models.CharField(blank=True, max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('origen_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.categoriamovimiento')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.cuenta')),
                ('origen_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Movimiento financiero',
                'verbose_name_plural': 'Movimientos financieros',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
