# Generated by Django 6.0.1 on 2026-04-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
    ]
