# Generated by Django 6.0.1 on 2026-02-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='cantidad_por_receta',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
