# Generated by Django 6.0.1 on 2026-02-23 18:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_receta_cantidad_por_receta'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='cantidad_producida',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='producto',
            field=models.ForeignKey(limit_choices_to={'tipo': 'PT'}, on_delete=django.db.models.deletion.PROTECT, to='stock.producto'),
        ),
    ]
