# Generated by Django 6.0.1 on 2026-02-02 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_empleado_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
