# Generated by Django 6.0.1 on 2026-03-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='created_at',
        ),
    ]
