# Generated by Django 6.0.1 on 2026-03-13 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_plato_created_at_remove_venta_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='plato',
            field=models.ForeignKey(limit_choices_to={'activo': 'True'}, on_delete=django.db.models.deletion.CASCADE, to='ventas.plato'),
        ),
    ]
